#!/bin/bash
clear

figlet post-commit

echo "Defining colors ..."
information=`tput setaf 2`
question=`tput setaf 3`
alert=`tput setaf 1`
reset=`tput sgr0`
echo "Colors defined ..."

echo ""
echo "${alert}Pay attention, this script aims to Auto-push branches on remote${reset}"

echo "${information}Retrieving current branch information ...${reset}"

currentBranch=$(git symbolic-ref -q HEAD)
currentBranch=${currentBranch##refs/heads/}
currentBranch=${currentBranch:-HEAD}
echo ""
echo "${information}Branch is $currentBranch ...${reset}"


if [ $currentBranch != 'master' ] || [ $currentBranch != 'testing' ] || [ $currentBranch != 'develop' ]; then
    git push origin $currentBranch -f;
else
    echo ""
    echo "${information}Update master!!!${reset}"
fi
